# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Conx < Formula
  desc ""
  homepage "https://github.com/nimbox/canexer-connector"
  version "2.0.10"

  on_macos do
    url "https://github.com/nimbox/conx/releases/download/v2.0.10/conx_2.0.10_darwin_all.tar.gz"
    sha256 "210d0c0e6138659adde435d01111715d910f425a5f9e707aa4667e5a30b850b8"

    def install
      bin.install "conx"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nimbox/conx/releases/download/v2.0.10/conx_2.0.10_linux_amd64.tar.gz"
        sha256 "78056900f42cf3993b9105b27507bcbf1a27fa112715cde4f0f812aa96e200f1"

        def install
          bin.install "conx"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nimbox/conx/releases/download/v2.0.10/conx_2.0.10_linux_arm64.tar.gz"
        sha256 "f64d6ed746209638da8d4808bd6aa39cedab93f3e504ccedf783c852691a7971"

        def install
          bin.install "conx"
        end
      end
    end
  end
end
