# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Conx < Formula
  desc ""
  homepage "https://github.com/nimbox/canexer-connector"
  version "2.0.9"

  on_macos do
    url "https://github.com/nimbox/conx/releases/download/v2.0.9/conx_2.0.9_darwin_all.tar.gz"
    sha256 "fad4264df6f168d0be3300226107f9be3ea4cd35660e44f001d7aa26d9ac6bca"

    def install
      bin.install "conx"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nimbox/conx/releases/download/v2.0.9/conx_2.0.9_linux_amd64.tar.gz"
      sha256 "265fa77f4c4b041766adc0ec2664d303cd32cec0f32613cb628c2f2c3ac4d9e5"

      def install
        bin.install "conx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nimbox/conx/releases/download/v2.0.9/conx_2.0.9_linux_arm64.tar.gz"
      sha256 "3de8329a7f4db56e9cabd2c8300d3c584f1b2013b62f8c56613f32714bd56177"

      def install
        bin.install "conx"
      end
    end
  end
end
