# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Conx < Formula
  desc ""
  homepage "https://github.com/nimbox/canexer-connector"
  version "1.0.10"

  on_macos do
    url "https://github.com/nimbox/conx/releases/download/v1.0.10/conx_1.0.10_darwin_all.tar.gz"
    sha256 "b3c1e3c41d80d04bbb5c46a75a91c601a40d375136fe003aae8d95a753fc1973"

    def install
      bin.install "conx"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nimbox/conx/releases/download/v1.0.10/conx_1.0.10_linux_arm64.tar.gz"
      sha256 "ed3dcdbcdede3901bef59c9d97906ac24cd4733ff7e8eb7fcedb3aa7773c0982"

      def install
        bin.install "conx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nimbox/conx/releases/download/v1.0.10/conx_1.0.10_linux_amd64.tar.gz"
      sha256 "3532543a7db0103c7441b15f763ec0c5a1cda0baa8f2a5d6b083d6838f27b978"

      def install
        bin.install "conx"
      end
    end
  end
end
