# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nimboxctl < Formula
  desc ""
  homepage "https://github.com/nimbox/nimboxctl"
  version "0.0.5"

  on_macos do
    url "https://github.com/nimbox/nimboxctl/releases/download/v0.0.5/nimboxctl_0.0.5_darwin_all.tar.gz"
    sha256 "0309715a4f0306c150eaf457e47c3fa347418eb1b015106d0ba1be13165389f7"

    def install
      bin.install "nimboxctl"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nimbox/nimboxctl/releases/download/v0.0.5/nimboxctl_0.0.5_linux_arm64.tar.gz"
      sha256 "f54d8b07068b84fea456058f8fe04d68f4f95da45d39e9f4a2d646361daa1bcb"

      def install
        bin.install "nimboxctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nimbox/nimboxctl/releases/download/v0.0.5/nimboxctl_0.0.5_linux_amd64.tar.gz"
      sha256 "63b62d243233e52b7e7a8123e9269ee06d477a43abdc7ba6f6f61d6e0c2b94c6"

      def install
        bin.install "nimboxctl"
      end
    end
  end
end
