# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nimboxctl < Formula
  desc ""
  homepage "https://github.com/nimbox/nimboxctl"
  version "0.0.23"

  on_macos do
    url "https://github.com/nimbox/nimboxctl/releases/download/v0.0.23/nimboxctl_0.0.23_darwin_all.tar.gz"
    sha256 "a8f949b0e3538439c4fc102afe5d4bf109a25c7b739eecd2549440dbcbcecd1e"

    def install
      bin.install "nimboxctl"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nimbox/nimboxctl/releases/download/v0.0.23/nimboxctl_0.0.23_linux_arm64.tar.gz"
      sha256 "fe70450b60e88a2e0f52e1f88f4297b6b08a42351ea3a8acff706a6f5f50a554"

      def install
        bin.install "nimboxctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nimbox/nimboxctl/releases/download/v0.0.23/nimboxctl_0.0.23_linux_amd64.tar.gz"
      sha256 "14fdd5a690cd1f478ef2caebe5476172fb999e522e8d255032aa5bc26045f754"

      def install
        bin.install "nimboxctl"
      end
    end
  end
end
